let strip = neopixel.create(DigitalPin.P0, 10, NeoPixelMode.RGB)
basic.showIcon(IconNames.Happy)
basic.forever(function () {
    strip.setPixelColor(7, neopixel.colors(NeoPixelColors.Red))
    strip.setPixelColor(8, neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(9, neopixel.colors(NeoPixelColors.Black))
    strip.show()
    basic.pause(2000)
    strip.setPixelColor(7, neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(8, neopixel.colors(NeoPixelColors.Yellow))
    strip.setPixelColor(9, neopixel.colors(NeoPixelColors.Black))
    strip.show()
    basic.pause(500)
    strip.setPixelColor(7, neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(8, neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(9, neopixel.colors(NeoPixelColors.Green))
    strip.show()
    servos.P1.setAngle(0)
    basic.pause(200)
    servos.P1.stop()
    basic.pause(2000)
    servos.P1.setAngle(180)
    basic.pause(200)
    servos.P1.stop()
})
